title: untitled63
email: 
description: The name comes from my tragic disposition to never name documents anything growing up. So it'd always be untitled-63.rtf or whatever.
baseurl: /
url: https://untitled63.com
permalink: pretty
sort_by: year, month
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
include: ['_pages']